language: python
python:
  - "2.7"
env:
  - DJANGO=1.4.8
  - DJANGO=1.5.4
install:
  - pip install -q Django==$DJANGO
  - pip install -q django-nose
  - pip install -q flake8
  - pip install -e .
script:
  - flake8 --max-line-length=100 --max-complexity=10 --statistics --benchmark notification
  - python runtests.py
