# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticetype',
            name='permission',
            field=models.CharField(blank=True, default='', help_text='Permission code "app_label.codename" to use for enabling this notice type', max_length=250),
        ),
    ]
